spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
