version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Up middleware by docker-compose"
      - chmod +x gradlew
      - ./gradlew setupTestEnv
  build:
    commands:
      - echo "Run test and build"
      - ./gradlew build
  post_build:
    commands:
      - echo "Up middleware by docker-compose"
      - ./gradlew cleanTestEnv

artifacts:
  files:
    - ./app/build/libs/app-0.0.1-SNAPSHOT.jar